#!/usr/bin/env bash

echo "installing and updating Wixed dependencies"
# Move to project root
cd ..

parentname="$(basename "$(pwd)")"
if [ ! $parentname = "Wixed" ] && [ ! $parentname = "weducedform" ]; then
  echo "Attempted setup from wrong directory -- move to wixed/bin!"
  exit 1
fi

if [ ! -d "lib" ]; then
  echo "Lib directory not present, exiting"
  exit 1
fi
cd "lib"


if [ -d 'Winterval' ]; then 
  rm -r 'Winterval'
fi
wget 'https://github.com/Willmo3/Winterval/raw/refs/heads/main/release/winterval-v0.0.4.tar.gz'
tar -xzf 'winterval-v0.0.4.tar.gz' && rm 'winterval-v0.0.4.tar.gz'

if [ -d 'Waffine' ]; then
  rm -r 'Waffine'
fi
wget 'https://github.com/Willmo3/Waffine/raw/refs/heads/main/release/waffine-v0.0.2.tar.gz'
tar -xzf 'waffine-v0.0.2.tar.gz' && rm 'waffine-v0.0.2.tar.gz'
