#!/usr/bin/env bash

echo "installing and updating Wixed dependencies"
# Move to project root
cd ..

parentname="$(basename "$(pwd)")"
if [ ! $parentname = "DualDomain" ] && [ ! $parentname = "weducedform" ]; then
  echo "Attempted setup from wrong directory -- move to dualdomain/bin!"
  exit 1
fi

if [ ! -d "lib" ]; then
  echo "Lib directory not present, exiting"
  exit 1
fi
cd "lib"

if [ -d 'Winterval' ]; then 
  rm -r 'Winterval'
fi
wget 'https://github.com/Willmo3/Winterval/raw/refs/heads/main/release/winterval-release.tar.gz'
tar -xzf 'winterval-release.tar.gz' && rm 'winterval-release.tar.gz'

if [ -d 'Caffeine' ]; then
  rm -r 'Caffeine'
fi
wget 'https://github.com/Willmo3/Caffeine/raw/refs/heads/main/release/caffeine-release.tar.gz'
tar -xzf 'caffeine-release.tar.gz' && rm 'caffeine-release.tar.gz'

if [[ -d "cereal" ]]; then
  rm -r "cereal"
fi

wget "https://github.com/USCiLab/cereal/archive/v1.3.2.tar.gz" && tar -xf "v1.3.2.tar.gz" && mv "cereal-1.3.2/include/cereal/" "." && rm -r cereal-1.3.2 v1.3.2.tar.gz

cd ..
